### ISSUE TITLE
install problem with 8.0.3.0.0

### ISSUE THREAD

**Issue by alanljj** [OCA/commission#102]
module: sale_commission
version: 8.0.3.0.0

**Steps to reproduce**
- upload addon
- clean all cookie and cache of browser
- update modules
- install

**Current behavior**
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 581, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 314, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 810, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 410, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/openerp/tools/convert.py", line 900, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/openerp/tools/convert.py", line 986, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 852, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 762, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_model.py", line 1069, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 257, in create
    context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 4100, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/opt/odoo/openerp/models.py", line 4297, in _create
    recs._validate_fields(vals)
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 1271, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` 违反约束(against a constraint): Invalid view definition

详细错误(Detailed Error)
Field `agents` does not exist

Error context:
View `res.partner.form.agent`
[view_id: 3437, xml_id: n/a, model: res.partner, parent_id: 126]" while parsing /opt/odoo/addons/sale_commission/views/res_partner_view.xml:5, near
<record id="view_partner_form_agent" model="ir.ui.view">
...

**Expected behavior**
But on my new fresh test environment, there is no problem with installation. How can I find the reason of this problem? thanks!

**Comment by pedrobaeza** [comment]
Old views should be automatically purged, but in this case, just remove them by SQL

**Comment by alanljj** [comment]
@pedrobaeza Thank you for your answer, could you please share a little more which views must be purged?

**Comment by pedrobaeza** [comment]
You have the view_id in the traceback.

**Comment by alanljj** [comment]
DELETE FROM ir_ui_view WHERE id = 3437;
DELETE 0
And the view_id changes every time, everytime I can't del it.
@pedrobaeza  May I ask wether my commond is wrong?

**Comment by pedrobaeza** [comment]
`parent_id: 126`

**Comment by alanljj** [comment]
@pedrobaeza look like there is no record for parent_id: 126. Thanks again! 
=> DELETE FROM res_partner WHERE parent_id = 126;
DELETE 0
Please give me more suggestion!

**Comment by pedrobaeza** [comment]
```
DELETE FROM res_partner WHERE inherit_id = 126;
DELETE FROM res_partner WHERE id = 126;
```

**Comment by alanljj** [comment]
@pedrobaeza  here is the result:
=> DELETE FROM res_partner WHERE id = 126;
DELETE 0
=> DELETE FROM res_partner WHERE inherit_id = 126;
ERROR:  column "inherit_id" does not exist
LINE 1: DELETE FROM res_partner WHERE inherit_id = 126;

**Comment by pedrobaeza** [comment]
Wow, I haven't seen the model!!
```
DELETE FROM ir_ui_view WHERE inherit_id = 126;
DELETE FROM ir_ui_view WHERE id = 126;
```

**Comment by alanljj** [comment]
@pedrobaeza  but the id 126 is a form view for Customer "res.partner.form", I can't delete it, many addons inherit from it.
It's blonge to base addon res_partner, is there any conflict with this model?

**Comment by pedrobaeza** [comment]
You should delete views and update your base module.

**Comment by alanljj** [comment]
@pedrobaeza  I found there are 40 form views inherit from id=126, that means I need uninstall all of this iherit addons, then I can delete id=126.

May I ask whether their have any solution update the sale_commission to solve this problem?

**Comment by pedrobaeza** [comment]
Sorry, I have already told you how to solve it.

**Comment by alanljj** [comment]
Anyway, I am really appricated you time, thank you very much!

**Comment by alanljj** [comment]
@pedrobaeza I come here to thank you for your suggestion.

after git pull latest source and updated the model base, it was installed successfully.

**Comment by pedrobaeza** [comment]
Good to know that.
