### ISSUE TITLE
Field `commission_id` does not exist

### ISSUE THREAD

**Issue by kootoo** [OCA/commission#22]
module: sale_commission
version: 8.0

**Steps to reproduce**
- I'm not really sure about this... I installed Etherpad + mysql, rebooted the server and did get this error with the sale_commission module. I tried to uninstall it and reinstall it with no chance, then tried to update it with no chance as well. I'm pretty sure there is no relationship with the Etherpad install.

**Current behavior**
I have the following errors that prevents me from accessing to Odoo and that loops.

2015-06-09 13:48:14,480 5306 ERROR datapro openerp.addons.base.ir.ir_ui_view: Field `commission_id` does not exist

Error context:
View `res.partner.form.agent`
[view_id: 2818, xml_id: sale_commission.view_partner_form_agent, model: res.partner, parent_id: 126]
2015-06-09 13:48:14,481 5306 ERROR datapro openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/odoo/newOCBtest/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/newOCBtest/openerp/http.py", line 1399, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1423, in match
    raise NotFound()
NotFound: 404: Not Found

**Expected behavior**
Well...

**Comment by kootoo** [comment]
Some more information... I was able to access again to Odoo (deleting addon, starting Odoo server, stopping Odoo, copying addon again, starting Odoo server). I tried to update it again and did get the following error messages. I hope this can help.

First set of error messages :
2015-06-10 05:51:32,081 12421 ERROR datapro openerp.addons.base.ir.ir_model: Missing model sale.agent
2015-06-10 05:51:32,082 12421 ERROR datapro openerp.addons.base.ir.ir_model: Missing model commission
2015-06-10 05:51:32,082 12421 ERROR datapro openerp.addons.base.ir.ir_model: Missing model settlement.agent
2015-06-10 05:51:32,083 12421 ERROR datapro openerp.addons.base.ir.ir_model: Missing model settled.invoice.agent
2015-06-10 05:51:32,095 12421 ERROR datapro openerp.addons.base.ir.ir_model: Missing model settlement

Second set of error messages :
2015-06-10 06:00:55,652 12421 ERROR datapro openerp.addons.base.ir.ir_ui_view: Le champ `commission_id` n'existe pas

Error context:
View `res.partner.form.agent`
[view_id: 11548, xml_id: sale_commission.view_partner_form_agent, model: res.partner, parent_id: 126]
2015-06-10 06:00:55,653 12421 ERROR datapro openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/odoo/newOCBtest/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/newOCBtest/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/home/odoo/newOCBtest/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/odoo/newOCBtest/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/odoo/newOCBtest/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/odoo/newOCBtest/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/home/odoo/newOCBtest/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/home/odoo/newOCBtest/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/newOCBtest/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/odoo/newOCBtest/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/newOCBtest/openerp/addons/base/module/module.py", line 537, in button_immediate_upgrade
    return self._button_immediate_function(cr, uid, ids, self.button_upgrade, context=context)
  File "/home/odoo/newOCBtest/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/newOCBtest/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/odoo/newOCBtest/openerp/modules/registry.py", line 368, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/newOCBtest/openerp/modules/loading.py", line 351, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/odoo/newOCBtest/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo/newOCBtest/openerp/modules/loading.py", line 192, in load_module_graph
    registry['ir.ui.view']._validate_module_views(cr, SUPERUSER_ID, module_name)
  File "/home/odoo/newOCBtest/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/newOCBtest/openerp/addons/base/ir/ir_ui_view.py", line 1140, in _validate_module_views
    if not self._check_xml(cr, uid, [vid]):
  File "/home/odoo/newOCBtest/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/newOCBtest/openerp/addons/base/ir/ir_ui_view.py", line 211, in _check_xml
    self.postprocess_and_fields(cr, uid, view.model, view_doc, view.id, context=context)
  File "/home/odoo/newOCBtest/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/newOCBtest/openerp/addons/base/ir/ir_ui_view.py", line 844, in postprocess_and_fields
    self.raise_view_error(cr, user, message, view_id, context)
  File "/home/odoo/newOCBtest/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/newOCBtest/openerp/addons/base/ir/ir_ui_view.py", line 369, in raise_view_error
    raise AttributeError(message)
AttributeError: Le champ `commission_id` n'existe pas

Error context:
View `res.partner.form.agent`
[view_id: 11548, xml_id: sale_commission.view_partner_form_agent, model: res.partner, parent_id: 126]

**Comment by pedrobaeza** [comment]
That field is not declared in the view: https://github.com/OCA/commission/blob/8.0/sale_commission/views/res_partner_view.xml#L5

So you should have an outdated database. Update it with --update=sale_commission or --update=all.
