### ISSUE TITLE
[11] sale_commission error cannot open sales order after installing

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/commission#225]
After installing sale_commission an  error appears if you try to open a sales order

Error:
Uncaught Error: , undefined as prefix

https://midominio.com/web/content/84490-85a8a3a/web.assets_backend.js:104
Rastreo de error:
Error: , undefined as prefix
    at F.nud (https://midominio.com/web/content/84490-85a8a3a/web.assets_backend.js:104:80)
    at expression (https://midominio.com/web/content/84490-85a8a3a/web.assets_backend.js:140:146)
    at F.symbol.nud (https://midominio.com/web/content/84490-85a8a3a/web.assets_backend.js:129:9)
    at expression (https://midominio.com/web/content/84490-85a8a3a/web.assets_backend.js:140:146)
    at Object.py.parse (https://midominio.com/web/content/84490-85a8a3a/web.assets_backend.js:257:462)
    at Object.py.eval (https://midominio.com/web/content/84490-85a8a3a/web.assets_backend.js:272:296)
    at https://midominio.com/web/content/84490-85a8a3a/web.assets_backend.js:377:110
    at iterator (https://midominio.com/web/content/83564-4d43a05/web.assets_common.js:14:183)
    at Function.<anonymous> (https://midominio.com/web/content/83564-4d43a05/web.assets_common.js:17:8)
    at _.<computed> [as reduce] (https://midominio.com/web/content/83564-4d43a05/web.assets_common.js:69:526)

**Comment by pedrobaeza** [comment]
Is this reproducible in runbot?

**Comment by RodrigoBM** [comment]
Yes @fgarcia-humanoide, 

I have the same problem, if you have the module https://github.com/OCA/sale-workflow/tree/11.0/sale_order_general_discount, this module not set the context right, the module add double comma to the context and this generate a error.

Regards.

**Comment by fgarcia-humanoide** [comment]
Thank you for your answer.

Yes , 

https://github.com/OCA/sale-workflow/tree/11.0/sale_order_general_discount

was installed.

**Comment by pedrobaeza** [comment]
Fixed in #229
