### ISSUE TITLE
[12.0][BUG?] sale_commisison,  key columns "commission" and "id" are of incompatible types

### ISSUE THREAD

**Issue by GSLabIt** [OCA/commission#251]
Hi there, i'm getting following error on runbot:

```
2020-07-20 11:08:20,257 901 ERROR openerp_test odoo.modules.registry: Failed to load registry
3454
Traceback (most recent call last):
3455
File "/github/home/odoo-12.0/odoo/modules/registry.py", line 86, in new
3456
odoo.modules.load_modules(registry._db, force_demo, status, update_module)
3457
File "/github/home/odoo-12.0/odoo/modules/loading.py", line 421, in load_modules
3458
loaded_modules, update_module, models_to_check)
3459
File "/github/home/odoo-12.0/odoo/modules/loading.py", line 313, in load_marked_modules
3460
perform_checks=perform_checks, models_to_check=models_to_check
3461
File "/github/home/odoo-12.0/odoo/modules/loading.py", line 195, in load_module_graph
3462
registry.init_models(cr, model_names, {'module': package.name})
3463
File "/github/home/odoo-12.0/odoo/modules/registry.py", line 300, in init_models
3464
model._auto_init()
3465
File "/github/home/odoo-12.0/odoo/models.py", line 2434, in _auto_init
3466
new = field.update_db(self, columns)
3467
File "/github/home/odoo-12.0/odoo/fields.py", line 901, in update_db
3468
self.update_db_column(model, column)
3469
File "/github/home/odoo-12.0/odoo/fields.py", line 920, in update_db_column
3470
sql.convert_column(model._cr, model._table, self.name, self.column_type[1])
3471
File "/github/home/odoo-12.0/odoo/tools/sql.py", line 92, in convert_column
3472
log_exceptions=False)
3473
File "/github/home/odoo-12.0/odoo/sql_db.py", line 148, in wrapper
3474
return f(self, *args, **kwargs)
3475
File "/github/home/odoo-12.0/odoo/sql_db.py", line 225, in execute
3476
res = self._obj.execute(query, params)
3477
psycopg2.ProgrammingError: foreign key constraint "res_partner_commission_fkey" cannot be implemented
3478
DETAIL:  Key columns "commission" and "id" are of incompatible types: double precision and integer.
```

Any hint on what's the issue?

**Comment by NL66278** [comment]
Might it be that you have an existing commission field in the res.partner model?

**Comment by GSLabIt** [comment]
At first check I didn't find it, will double check and get back

**Comment by NL66278** [comment]
Please check the table itself (in psql), the field might not be present in the current code, but still be in the table.

**Comment by GSLabIt** [comment]
Will do, but it is a runbot so it is builded from scratch every time

**Comment by GSLabIt** [comment]
> Please check the table itself (in psql), the field might not be present in the current code, but still be in the table.

You where right i got `commission`field in another module. 

What about to modify `commission` in `commission_id` as it refer to and object?

**Comment by NL66278** [comment]
It seems a good idea to me to use commission_id, but I am not involved in the development of these modules. You could make a PR for this.

**Comment by GSLabIt** [comment]
I could do a PR, @pedrobaeza what you think?

**Comment by pedrobaeza** [comment]
The renaming has been done already in v13, so you can't do that this in v12 without having to trick too much.

**Comment by GSLabIt** [comment]
what about a backport from 13?

**Comment by pedrobaeza** [comment]
I think a better solution is that you rename the other field in your custom module, as it's not easy to handle this in OCA and there's no problem inside OCA itself, so I'm closing this issue now.

**Comment by GSLabIt** [comment]
ok
