### ISSUE TITLE
[13] sale_commission_pricelist

### ISSUE THREAD

**Issue by ghost** [OCA/commission#253]
During the instalation of the module this traceback appears:
<details>
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo13-pre/odoo/odoo/addons/base/models/ir_ui_view.py", line 664, in apply_inheritance_specs
    pre_locate=pre_locate)
  File "/opt/odoo13-pre/odoo/odoo/tools/template_inheritance.py", line 230, in apply_inheritance_specs
    _("Element '%s' cannot be located in parent view") % tag
ValueError: El elemento '<xpath expr="//tree/field[@name='fixed_price']">' no puede ser localizado en la vista padre

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo13-pre/odoo/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/opt/odoo13-pre/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/opt/odoo13-pre/odoo/odoo/tools/convert.py", line 577, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/opt/odoo13-pre/odoo/odoo/models.py", line 4084, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo13-pre/odoo/odoo/models.py", line 3998, in _load_records_create
    return self.create(values)
  File "<decorator-gen-146>", line 2, in create
  File "/opt/odoo13-pre/odoo/odoo/api.py", line 317, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo13-pre/odoo/odoo/api.py", line 317, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo13-pre/odoo/enterprise/web_studio/models/studio_mixin.py", line 19, in create
    res = super(StudioMixin, self).create(vals)
  File "<decorator-gen-32>", line 2, in create
  File "/opt/odoo13-pre/odoo/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo13-pre/odoo/odoo/addons/base/models/ir_ui_view.py", line 475, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo13-pre/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo13-pre/odoo/odoo/models.py", line 3779, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo13-pre/odoo/odoo/fields.py", line 1120, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo13-pre/odoo/odoo/addons/base/models/ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "/opt/odoo13-pre/odoo/addons/website_theme_install/models/theme_models.py", line 226, in write
    res = super(IrUiView, other_views).write(vals)
  File "/opt/odoo13-pre/odoo/addons/website/models/ir_ui_view.py", line 51, in write
    return super(View, self).write(vals)
  File "/opt/odoo13-pre/odoo/enterprise/web_studio/models/studio_mixin.py", line 28, in write
    res = super(StudioMixin, self).write(vals)
  File "/opt/odoo13-pre/odoo/odoo/addons/base/models/ir_ui_view.py", line 493, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo13-pre/odoo/odoo/models.py", line 3568, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/opt/odoo13-pre/odoo/odoo/models.py", line 1176, in _validate_fields
    check(self)
  File "/opt/odoo13-pre/odoo/odoo/addons/base/models/ir_ui_view.py", line 387, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/opt/odoo13-pre/odoo/odoo/addons/base/models/ir_ui_view.py", line 738, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/opt/odoo13-pre/odoo/odoo/addons/base/models/ir_ui_view.py", line 687, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/opt/odoo13-pre/odoo/enterprise/web_studio/models/ir_ui_view.py", line 154, in apply_inheritance_specs
    pre_locate=pre_locate)
  File "/opt/odoo13-pre/odoo/odoo/addons/base/models/ir_ui_view.py", line 666, in apply_inheritance_specs
    self.raise_view_error(str(e), inherit_id)
  File "/opt/odoo13-pre/odoo/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
ValueError: El elemento '<xpath expr="//tree/field[@name='fixed_price']">' no puede ser localizado en la vista padre

Contexto del error:
Vista `product.pricelist form`
[view_id: 2096, xml_id: n/a, model: product.pricelist, parent_id: 503]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo13-pre/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13-pre/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13-pre/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13-pre/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13-pre/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13-pre/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13-pre/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13-pre/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13-pre/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13-pre/odoo/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo13-pre/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo13-pre/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo13-pre/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-60>", line 2, in button_immediate_install
  File "/opt/odoo13-pre/odoo/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo13-pre/odoo/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo13-pre/odoo/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo13-pre/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo13-pre/odoo/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo13-pre/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo13-pre/odoo/odoo/modules/loading.py", line 225, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo13-pre/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo13-pre/odoo/odoo/tools/convert.py", line 736, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo13-pre/odoo/odoo/tools/convert.py", line 803, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/odoo13-pre/odoo/odoo/tools/convert.py", line 721, in parse
    exc_info[2]
  File "/opt/odoo13-pre/odoo/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo13-pre/odoo/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/opt/odoo13-pre/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/opt/odoo13-pre/odoo/odoo/tools/convert.py", line 577, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/opt/odoo13-pre/odoo/odoo/models.py", line 4084, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo13-pre/odoo/odoo/models.py", line 3998, in _load_records_create
    return self.create(values)
  File "<decorator-gen-146>", line 2, in create
  File "/opt/odoo13-pre/odoo/odoo/api.py", line 317, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo13-pre/odoo/odoo/api.py", line 317, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo13-pre/odoo/enterprise/web_studio/models/studio_mixin.py", line 19, in create
    res = super(StudioMixin, self).create(vals)
  File "<decorator-gen-32>", line 2, in create
  File "/opt/odoo13-pre/odoo/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo13-pre/odoo/odoo/addons/base/models/ir_ui_view.py", line 475, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo13-pre/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo13-pre/odoo/odoo/models.py", line 3779, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo13-pre/odoo/odoo/fields.py", line 1120, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo13-pre/odoo/odoo/addons/base/models/ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "/opt/odoo13-pre/odoo/addons/website_theme_install/models/theme_models.py", line 226, in write
    res = super(IrUiView, other_views).write(vals)
  File "/opt/odoo13-pre/odoo/addons/website/models/ir_ui_view.py", line 51, in write
    return super(View, self).write(vals)
  File "/opt/odoo13-pre/odoo/enterprise/web_studio/models/studio_mixin.py", line 28, in write
    res = super(StudioMixin, self).write(vals)
  File "/opt/odoo13-pre/odoo/odoo/addons/base/models/ir_ui_view.py", line 493, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo13-pre/odoo/odoo/models.py", line 3568, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/opt/odoo13-pre/odoo/odoo/models.py", line 1176, in _validate_fields
    check(self)
  File "/opt/odoo13-pre/odoo/odoo/addons/base/models/ir_ui_view.py", line 387, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/opt/odoo13-pre/odoo/odoo/addons/base/models/ir_ui_view.py", line 738, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/opt/odoo13-pre/odoo/odoo/addons/base/models/ir_ui_view.py", line 687, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/opt/odoo13-pre/odoo/enterprise/web_studio/models/ir_ui_view.py", line 154, in apply_inheritance_specs
    pre_locate=pre_locate)
  File "/opt/odoo13-pre/odoo/odoo/addons/base/models/ir_ui_view.py", line 666, in apply_inheritance_specs
    self.raise_view_error(str(e), inherit_id)
  File "/opt/odoo13-pre/odoo/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
odoo.tools.convert.ParseError: "El elemento '<xpath expr="//tree/field[@name='fixed_price']">' no puede ser localizado en la vista padre

Contexto del error:
Vista `product.pricelist form`
[view_id: 2096, xml_id: n/a, model: product.pricelist, parent_id: 503]" while parsing /opt/odoo13-pre/OCA/commission/sale_commission_pricelist/views/product_pricelist_view.xml:4, near
<odoo>
    <record id="product_pricelist_item_tree_view" model="ir.ui.view">
        <field name="model">product.pricelist.item</field>
        <field name="inherit_id" ref="product.product_pricelist_item_tree_view"/>
        <field name="arch" type="xml">
            <field name="min_quantity" position="after">
                <field name="commission_id"/>
            </field>
        </field>
    </record>
    <record id="product_pricelist_item_form_view" model="ir.ui.view">
        <field name="model">product.pricelist.item</field>
        <field name="inherit_id" ref="product.product_pricelist_item_form_view"/>
        <field name="arch" type="xml">
            <field name="min_quantity" position="after">
                <field name="commission_id"/>
            </field>
        </field>
    </record>
    <record id="product_pricelist_view" model="ir.ui.view">
        <field name="model">product.pricelist</field>
        <field name="inherit_id" ref="product.product_pricelist_view"/>
        <field name="arch" type="xml">
            <xpath expr="//tree/field[@name='fixed_price']" position="after">
                <field name="commission_id"/>
            </xpath>
        </field>
    </record>
</odoo>
</details>
I think this module is not compatible with the base view of Odoo product.product_pricelist_view_inherit

UPDATED: in runbot works properly

**Comment by ghost** [comment]
I have check it on runbot and the problem is when pricelists are activated.It cna be checked on this video.
https://drive.google.com/file/d/1p7XDqVFtbkBI8PBcwbFG7EHpaLdoyc4J/view

The traceback is:
<details>
Odoo Server Error
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 664, in apply_inheritance_specs
    pre_locate=pre_locate)
  File "/.repo_requirements/odoo/odoo/tools/template_inheritance.py", line 230, in apply_inheritance_specs
    _("Element '%s' cannot be located in parent view") % tag
ValueError: Element '<xpath expr="//tree/field[@name='fixed_price']">' cannot be located in parent view

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/.repo_requirements/odoo/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/.repo_requirements/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/models.py", line 1441, in load_views
    for [v_id, v_type] in views
  File "/.repo_requirements/odoo/odoo/models.py", line 1441, in <dictcomp>
    for [v_id, v_type] in views
  File "/.repo_requirements/odoo/addons/web/models/models.py", line 206, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/.repo_requirements/odoo/odoo/models.py", line 1521, in fields_view_get
    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/.repo_requirements/odoo/odoo/models.py", line 1483, in _fields_view_get
    root_view = View.browse(view_id).read_combined(['id', 'name', 'field_parent', 'type', 'model', 'arch'])
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 738, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 687, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 666, in apply_inheritance_specs
    self.raise_view_error(str(e), inherit_id)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
ValueError: Element '<xpath expr="//tree/field[@name='fixed_price']">' cannot be located in parent view

Error context:
View `product.pricelist form`
[view_id: 850, xml_id: sale_commission_pricelist.product_pricelist_view, model: product.pricelist, parent_id: 450]
</details>
