### ISSUE TITLE
[13.0] sale_commission: Does not work on print settlement report

### ISSUE THREAD

**Issue by SmithLin0618** [OCA/commission#254]
Impacted versions:

At 13.0

Steps to reproduce:

![image](https://user-images.githubusercontent.com/38001362/88861486-a5ca8e80-d230-11ea-9444-97ae9a87fc0c.png)

![image](https://user-images.githubusercontent.com/38001362/88861503-b0852380-d230-11ea-8b05-83db75da8931.png)
--------------------------------------
Copy the full error：
--------------------------------------
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/models.py", line 5000, in ensure_one
    _id, = self._ids
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_sale_commission_report_settlement_1573
  File "<template>", line 2, in body_call_content_1571
  File "<template>", line 3, in foreach_1570
  File "<template>", line 4, in body_call_content_1568
  File "<template>", line 31, in foreach_1566
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb.py", line 382, in _get_field
    content = converter.record_to_html(record, field_name, field_options)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb_fields.py", line 464, in record_to_html
    return super(MonetaryConverter, self).record_to_html(record, field_name, options)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb_fields.py", line 128, in record_to_html
    return False if value is False else record.env[self._name].value_to_html(value, options=options)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb_fields.py", line 434, in value_to_html
    formatted_amount = lang.format(fmt, display_currency.round(value),
  File "/odoo/odoo-server/odoo/addons/base/models/res_currency.py", line 132, in round
    self.ensure_one()
  File "/odoo/odoo-server/odoo/models.py", line 5003, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: res.currency()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 2025, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1963, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/odoo/odoo-server/odoo/addons/base/models/ir_actions_report.py", line 728, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/odoo/odoo-server/odoo/addons/base/models/ir_actions_report.py", line 768, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/odoo/odoo-server/odoo/addons/base/models/ir_actions_report.py", line 542, in render_template
    return view_obj.render_template(template, values)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 1177, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/odoo/odoo-server/addons/web_editor/models/ir_ui_view.py", line 25, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 1185, in render
    return self.env[engine].render(self.id, qcontext)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 339, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: Expected singleton: res.currency()
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/models.py", line 5000, in ensure_one
    _id, = self._ids
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 332, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_sale_commission_report_settlement_1573
  File "<template>", line 2, in body_call_content_1571
  File "<template>", line 3, in foreach_1570
  File "<template>", line 4, in body_call_content_1568
  File "<template>", line 31, in foreach_1566
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb.py", line 382, in _get_field
    content = converter.record_to_html(record, field_name, field_options)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb_fields.py", line 464, in record_to_html
    return super(MonetaryConverter, self).record_to_html(record, field_name, options)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb_fields.py", line 128, in record_to_html
    return False if value is False else record.env[self._name].value_to_html(value, options=options)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb_fields.py", line 434, in value_to_html
    formatted_amount = lang.format(fmt, display_currency.round(value),
  File "/odoo/odoo-server/odoo/addons/base/models/res_currency.py", line 132, in round
    self.ensure_one()
  File "/odoo/odoo-server/odoo/models.py", line 5003, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: res.currency()

Error to render compiling AST
ValueError: Expected singleton: res.currency()
Template: sale_commission.report_settlement
Path: /t/t/t/t/div/table/tbody/tr/td[5]/span
Node: <span t-field="l.settled_amount" t-field-options="{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: &quot;o.currency_id&quot;}"/>

**Comment by sergioeix** [comment]
I have this error too and its fully reproducible on runbot, it will be awesome if the maintainer @pedrobaeza could check it when he will be avaible and have the time.
B/R

**Comment by pedrobaeza** [comment]
Fixed in 60e9ce185ca407601a431eb006ff8e5efdc6ed58
