### ISSUE TITLE
[13] Community sale_commission_pricelist install ERROR

### ISSUE THREAD

**Issue by sergioeix** [OCA/commission#259]
Odoo 13 community
Ubuntu 18
When I try to install the module when pricelist option on sales is Multiple prices per product, module install succesfully, but when i change option to Advanced price rules and go sales-products-pricelist shows this trace back
Traceback:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 664, in apply_inheritance_specs
    pre_locate=pre_locate)
  File "/opt/odoo13/odoo/odoo/tools/template_inheritance.py", line 230, in apply_inheritance_specs
    _("Element '%s' cannot be located in parent view") % tag
ValueError: Element '<xpath expr="//tree/field[@name='fixed_price']">' cannot be located in parent view

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo-custom-addons/ks_list_view_manager/controllers/lvm_controller.py", line 16, in call_kw
    call_kw_result = super(LvmController, self).call_kw(model, method, args, kwargs, path)
  File "/opt/odoo13/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/models.py", line 1441, in load_views
    for [v_id, v_type] in views
  File "/opt/odoo13/odoo/odoo/models.py", line 1441, in <dictcomp>
    for [v_id, v_type] in views
  File "/opt/odoo13/odoo/addons/web/models/models.py", line 206, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/opt/odoo13/odoo/odoo/models.py", line 1521, in fields_view_get
    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/opt/odoo13/odoo/odoo/models.py", line 1483, in _fields_view_get
    root_view = View.browse(view_id).read_combined(['id', 'name', 'field_parent', 'type', 'model', 'arch'])
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 738, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 687, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 666, in apply_inheritance_specs
    self.raise_view_error(str(e), inherit_id)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
ValueError: Element '<xpath expr="//tree/field[@name='fixed_price']">' cannot be located in parent view

Error context:
View `product.pricelist form`
[view_id: 3244, xml_id: sale_commission_pricelist.product_pricelist_view, model: product.pricelist, parent_id: 466]

When i try to install module with sale pricelist setting set on Advanced price rules, install fail and show the same traceback.

Anyone can help?

**Comment by pedrobaeza** [comment]
@eLBati can you please check?

**Comment by eLBati** [comment]
Maybe @feketemihai is more suitable to check as he ported `sale_commission_pricelist` to v13 while I don't use v13

**Comment by pedrobaeza** [comment]
Right, I confused the porter, sorry.

**Comment by feketemihai** [comment]
@pedrobaeza @eLBati i can check it but only next week, Monday.

**Comment by sergioeix** [comment]
Hello @feketemihai , any news ? This error can be reproduced on runbot, just enable pricelist formula option and try to go sales pricelist menu
B/R

**Comment by sergioeix** [comment]
this was forgotten ??
B/R

**Comment by feketemihai** [comment]
@sergioeix The fix is in https://github.com/OCA/commission/pull/261

**Comment by sergioeix** [comment]
@feketemihai i will try this ty
