### ISSUE TITLE
Error in module

### ISSUE THREAD

**Issue by diiman2000** [OCA/commission#41]
Hi,
There is an error in the module, when a quotation is created and you add an agent and confirm the quotation, the agent added is not been forwarded to the invoice of that sale order under accounting, you need to manually do it again under the invoice even if you originally added the agent in the quotation. when u now add the agent in the invoice area it come up with an error.

**Comment by diiman2000** [comment]
This is the error i get when the agent is added during the invoice process
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo1/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo1/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 372, in old_api
    result = method(recs, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5916, in onchange
    record = self.new(values)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5480, in new
    record._cache.update(record._convert_to_cache(values, update=True))
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5375, in _convert_to_cache
    for name, value in values.iteritems()
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5376, in <dictcomp>
    if name in fields
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 1645, in convert_to_cache
    ids = OrderedSet(command[2])
  File "/usr/lib/python2.7/dist-packages/openerp/tools/misc.py", line 1282, in __init__
    super(OrderedSet, self).**init**([(x, None) for x in seq])
TypeError: 'NoneType' object is not iterable

**Comment by pedrobaeza** [comment]
This error is nothing related with the module itself, but with your installation. Try to restart your server and be sure that you're using the correct version (8.0) in both the module and the server.
