### ISSUE TITLE
Error when editing invoice lines

### ISSUE THREAD

**Issue by ivantodorovich** [OCA/commission#62]
I'm getting this error when **editing** invoice lines.

**Steps to reproduce:**
1. Create an invoice with commissions
2. Save it (but don't validate)
3. Open and Edit the invoice
4. Edit some invoice line quantity or product. Maybe also click the invoice line agent lines.
5. Try to save the line (lose focus)

This error window raises 3 times:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/itodorovich/odoo/server/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/itodorovich/odoo/server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/api.py", line 387, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/models.py", line 5920, in onchange
    record = self.new(values)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/api.py", line 254, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/models.py", line 5484, in new
    record._cache.update(record._convert_to_cache(values, update=True))
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/models.py", line 5379, in _convert_to_cache
    for name, value in values.iteritems()
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/models.py", line 5380, in <dictcomp>
    if name in fields
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/fields.py", line 1645, in convert_to_cache
    ids = OrderedSet(command[2])
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/tools/misc.py", line 1282, in __init__
    super(OrderedSet, self).__init__([(x, None) for x in seq])
TypeError: 'NoneType' object is not iterable
```

Also, not always, but continuing to mess with the invoice lines causes some other errors. For instance, this one:

```
Odoo Error del Cliente
Uncaught TypeError: Cannot read property 'constructor' of undefined
http://192.168.1.110:8069/web/js/web.assets_backend/45bced3:2918
```

**Comment by pedrobaeza** [comment]
This kind of errors happens on the web client side, so there's nothing to do with the current commission code to solve it, but it will be more predictable if we don't use a one2many inside another one2many. Is there something that you figure out for avoiding this one2many?

**Comment by ivantodorovich** [comment]
Hmm..

**To avoid it**
I've saw a comment from you in a PR, suggesting to hide commissions lines from invoices with a security group. It's isn't really a fix, but it would avoid errors showing up 99.99% of the times. Since it's almost never needed to edit invoice line comissions manually.

**To possible fix it**

Maybe we can show a tags-like field where each tag represents a combination of agent and commission. There could be a small button to open a wizard an edit agent lines. I don't know if its possible, though.

**Another way to avoid it..**

Our use case for commissions is a lot simpler than what's implemented. For instance, we should never set more than 1 commission per invoice line. 
Also the agent is a constant in every line, it's only set on a sales order / invoice level.

Maybe we could split this module in 2, provinding a more simple and general approach in the base module and support for multiple agent lines per invoice line in another module.

Again, this isn't a fix. It's rather a workaround for companies that don't need complex commission schemes.

**Comment by pedrobaeza** [comment]
Yeah, they're workarounds (the last 2, the first one is only to hide the elements) and some of them not easily feasible, but we should find a solution. Let's think a bit more...

**Comment by ivantodorovich** [comment]
No great ideas from this brain, right now. Maybe something will come up in my sleep.

For now, I'll investigate how security groups work and make a PR, since our company needs some kind of workaround to this error. I mean, hiding is enough to avoid it, right? Or will it still raise errors?

**Comment by ivantodorovich** [comment]
Related https://github.com/OCA/commission/issues/49 & https://github.com/OCA/commission/issues/25 & https://github.com/OCA/commission/issues/52

**Comment by ivantodorovich** [comment]
https://github.com/OCA/commission/pull/78 will probably solve it.
